### ISSUE TITLE
任务不执行？

### ISSUE THREAD

**Issue by ssbg2** [Dreampie/jfinal-quartz#1]
您好，谢谢您做出的贡献，学习您的代码让我受益良多。
现在有一个问题，使用jfinal-quartz插件写定时任务，会有下面的日志：
`894 [RMI TCP Connection(5)-127.0.0.1] INFO org.quartz.impl.StdSchedulerFactory - Using default implementation for ThreadExecutor
934 [RMI TCP Connection(5)-127.0.0.1] INFO org.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
934 [RMI TCP Connection(5)-127.0.0.1] INFO org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.2.1 created.
936 [RMI TCP Connection(5)-127.0.0.1] INFO org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
937 [RMI TCP Connection(5)-127.0.0.1] INFO org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.2.1) 'defaultScheduler' with instanceId 'default'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 5 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

937 [RMI TCP Connection(5)-127.0.0.1] INFO org.quartz.impl.StdSchedulerFactory - Quartz scheduler 'defaultScheduler' initialized from an externally provided properties instance.
937 [RMI TCP Connection(5)-127.0.0.1] INFO org.quartz.impl.StdSchedulerFactory - Quartz scheduler version: 2.2.1
937 [RMI TCP Connection(5)-127.0.0.1] INFO org.quartz.core.QuartzScheduler - Scheduler defaultScheduler_$_default started.`

关键地方是这几句，
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
配置文件这么写的：
`a.job=com.jfinalRestApi.job.OrderCheck

a.cron=0/59 * * * * ?

a.enable=true`

我还试了
new QuartzCronJob(new QuartzKey(1, "test", "test"), "*/5 * * * * ?", DemoJob.class)
这样的方法，没有什么变化，请问我下一步应该怎么排查错误？
谢谢！

**Comment by Dreampie** [comment]
查看test目录，对比配置
